print("Welcome to the Band Name Generator.")
city = input("What's the name of the city you grew up in?\n")
print(city)
pet_name = input("What's your first pet's name?\n")
print(pet_name)
print("Your band name could be " + city + " " + pet_name)
